/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddProductForm: typeof import('./src/components/AddProductForm.vue')['default']
    EditProductForm: typeof import('./src/components/EditProductForm.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ProductCard: typeof import('./src/components/ProductCard.vue')['default']
    ProductsList: typeof import('./src/components/ProductsList.vue')['default']
  }
}
